name: Movies Preview Feature Branch Checks

on: 
  push:
    branches:
      - '*'
      - '!master'

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Unit Tests
      run: bash ./gradlew test --stacktrace

  health-check:
    name: Health Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Deteckt
        run: bash ./gradlew detekt
      - name: Run Ktlint
        run: bash ./gradlew ktlint
      - name: Run Lint
        run: bash ./gradlew lintDebug
      - name: Run Unit Tests
        run: bash ./gradlew test --stacktrace

  run-integration-tests:
     name: Run Integration Tests
     runs-on: macOS-latest

     steps:
       - name: checkout
         uses: actions/checkout@v2

       - name: run tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: 29
           script: ./gradlew connectedAndroidTest

       - name: Upload results
         uses: actions/upload-artifact@v1
         with:
           name: app
           path: file:///Users/runner/runners/2.164.0/work/moviespreview/moviespreview/app/build/reports/androidTests/connected/index.html