name: Movies Preview Feature Branch CI

on: 
  push:
    branches: 
      - '*'
      - '!master'

jobs:
  build:
    
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Deteckt
      run: bash ./gradlew detekt
    - name: Run Ktlint
      run: bash ./gradlew ktlint
    - name: Run Lint
      run: bash ./gradlew lintDebug
    - name: Run Unit Tests
      run: bash ./gradlew test --stacktrace
